version: '3'
services:
  fatmadatabase:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devops
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
  backend:
    depends_on:
      - fatmadatabase
    build: ./
    restart: on-failure
    ports:
      - "8090:8082"
    stdin_open: true
    tty: true
    volumes:
      - .m2:/root/.m2
volumes:
  db: