version: '3.7'

services:
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_password_secret
      - MYSQL_DATABASE=devopsdb
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    secrets:
      - db_password_secret

  backend:
    depends_on:
      - mysqldb
    image: fedii97/devopsproject-0.0.1.jar
    restart: on-failure
    ports:
      - "8090:8089"
    stdin_open: true
    tty: true
    volumes:
      - .m2:/root/.m2

secrets:
  db_password_secret:
    external: true
